USE chatdb;
CREATE TABLE users(id INT AUTO_INCREMENT PRIMARY KEY,username VARCHAR(20) UNIQUE NOT NULL,password VARCHAR(255) NOT NULL,last_seen TIMESTAMP NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE rooms(id INT AUTO_INCREMENT PRIMARY KEY,is_group TINYINT NOT NULL DEFAULT 0,name VARCHAR(40) NULL,created_by INT);
CREATE TABLE room_members(room_id INT,user_id INT,PRIMARY KEY(room_id,user_id));
CREATE TABLE messages(id INT AUTO_INCREMENT PRIMARY KEY,room_id INT NOT NULL,user_id INT NOT NULL,body TEXT NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,INDEX(room_id,id));
